# use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
      - $HOME/.m2/repository
      - $HOME/.sbt
      - $HOME/.ivy2

language: scala
scala:
# When updating Scala versions, also check the excludes
# in build matrix below.
#- 2.11.12
- 2.12.4
jdk:
- oraclejdk8
  #- oraclejdk9

script: 
  - sbt ++$TRAVIS_SCALA_VERSION test

#env:
#  matrix:
#    - SCRIPT=scripts/test-sbt
#    - SCRIPT=scripts/test-gradle
#script:
#- $SCRIPT
#cache:
#  directories:
#  - "$HOME/.ivy2/cache"
#  - "$HOME/.gradle/caches"
#before_cache:
#- rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
#- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
#- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm


