version: '3.3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: jianfeng
      POSTGRES_PASSWORD: password
      POSTGRES_DB: activity

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "9000:9000"
    depends_on:
      - db
